# Generated by Django 5.1.15 on 2026-02-07 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('view', '0002_quizuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizProgress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100)),
                ('set_number', models.IntegerField()),
                ('current_index', models.IntegerField(default=0)),
                ('user_answers', models.JSONField(default=dict)),
                ('time_spent', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'unique_together': {('user_name', 'set_number')},
            },
        ),
    ]
