# Generated by Django 6.0.2 on 2026-02-10 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('view', '0003_quizprogress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizprogress',
            name='current_index',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='quizprogress',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='quizprogress',
            name='set_number',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='quizprogress',
            name='time_spent',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='quizscore',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='quizscore',
            name='score',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='quizscore',
            name='set_number',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='quizscore',
            name='total_questions',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='quizuser',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
