name: Django CI with Ngrok

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.13"

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Install Ngrok
      run: |
        wget https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-linux-amd64.tgz
        tar -xvzf ngrok-v3-stable-linux-amd64.tgz
        sudo mv ngrok /usr/local/bin

    - name: Configure Ngrok
      run: |
        ngrok config add-authtoken 35Pwg1olsf7fGkQkiBWhvqo8kJ6_5x6ag9s7ceQEhhtPPwMFE

    - name: Start Django Server
      run: |
        python manage.py runserver 0.0.0.0:8000 &
    
    - name: Start Ngrok Tunnel
      run: |
        ngrok http 8000 &
        sleep 10
        curl http://localhost:4040/api/tunnels
